### ISSUE TITLE
Hi Nikita, has the interface changed again?

### ISSUE THREAD

**Issue by jobsfan** [Hormold/pubg#11]
I remember that it changed from entry.playbattlegrounds.com:81 to prod-live-entry.playbattlegrounds.com.

Has it changed again? I got an open error now when I start to run the entrance code.

Error connecting: 

Wish you kind reply!

**Comment by Hormold** [comment]
Hi. Yes, i too have a problem with connection. Still no solution. Websocket endpoint is still prod-live-entry.playbattlegrounds.com.
Checkout: https://prod-live-front.playbattlegrounds.com/app/pc-1.6-20180322-2018.03.23-2199/index-steam.pc-1.6-20180322-2018.03.23-2199.html

**Comment by NeOMakinG** [comment]
ws://prod-live-entry.playbattlegrounds.com:81/userproxy or wss://prod-live-entry.playbattlegrounds.com/userproxy is the new entry ;)

**Comment by NeOMakinG** [comment]
it looks like it has a /userproxy now at the end

**Comment by Hormold** [comment]
Just add this to params
 ```
  { 'cc': 'RU',
      'clientGameVersion': "3.7.20",
      'fullClientGameVersion': '3.7.20',
      'timezoneOffset':'2'}
```

**Comment by jobsfan** [comment]
It works! Oops, your are so expert on this! Big Gun! Thank you so much!
