### ISSUE TITLE
endpoints

### ISSUE THREAD

**Issue by busheezy** [Hormold/pubg#13]
Does anyone know the new endpoints or perhaps there are more changes than that.

**Comment by jobsfan** [comment]
we met a situation that, even though we set the latest version no , it still break down. @Hormold , Have you encountered this? Any good ideas?

**Comment by busheezy** [comment]
I ended up getting mine working. I was just had a small silly error that worked prior to today.

**Comment by jobsfan** [comment]
@busheezy 
How did you fix the problem? 
let query = { }
Is the query params changed? Or the server interface changed?

**Comment by busheezy** [comment]
I wasn't passing the game version that I had stored in my config. The socket closing was with the reason something about upgrade.

**Comment by jobsfan** [comment]
@busheezy  are you using @Hormold 's code, with a run.js and a setting.js?
I have no idea about "The socket closing was with the reason something about upgrade" you said.
Does this mean that the server interface[prod-live-entry.playbattlegrounds.com] changed?

**Comment by busheezy** [comment]
Currently, with the updated readme, my proxy works entirely without any
changes.

**Comment by jobsfan** [comment]
@busheezy 
Is the query params changed?

let query = { 'provider': 'steam', 'ticket': settings.ticket, 'playerNetId': settings.steamId, 'cc': 'RU', 'clientGameVersion': settings.v, 'fullClientGameVersion':settings.v2, 'timezoneOffset':'2'};

Last time, @Hormold  told me to change the query params like that. Pls tell me. It bother me a lot.

**Comment by busheezy** [comment]
You have what I was missing.

```ts
    const queryString = qs.stringify({
      provider,
      cc,
      clientGameVersion,
      fullClientGameVersion,
      ticket: this._ticket,
      playerNetId: this._steamid,
    });

    this._url = `wss://prod-live-entry.playbattlegrounds.com/userproxy?${queryString}`;
```

**Comment by jobsfan** [comment]
@busheezy  It seems you have the same setting with mine.  More or less, I have a timezoneOffset that you don't have, and you have v param that I miss. Can you tell me what does your v mean? Is it a const?

**Comment by busheezy** [comment]
I'm sorry. I removed it from the post because it wasn't meant to be there.

**Comment by busheezy** [comment]
I believe the servers are actually down for maintenance. My client doesn't even connect, at the moment.

**Comment by jobsfan** [comment]
@busheezy Ok, so, can you tell me what's your 'v' means in your queries? Is it the same with clientGameVersion or fullClientGameVersion?

**Comment by zyi1992** [comment]
Seems like pubg server was check the client version now, so you must keep the version be newest ，and as the bluehole update server almost everyday, it would be a hard work for you to keep it. but if anyone find a way to get the newest version, i would be so appreciate if  anyone share it.
