### ISSUE TITLE
Invalid Auth

### ISSUE THREAD

**Issue by Spechen** [Hormold/pubg#14]
Hello, for this morning i can't connect the app to PUBG, since the last update 3.8.22.4

The server returns this error : `Error connecting: AR:INVALID_AUTH_DATA_ERROR`

The link to connect takes `clientGameVersion` and `fullClientGameVersion`

Thanks for helping me

**Comment by boomix** [comment]
Check your steamID64, there might be some problem steam-user libary. For me the playerNetId was null, thats why it was giving this error.

**Comment by Spechen** [comment]
Thanks you, it works
I don't know why, without steamID it worked yesterday but not this morning

Thank you so much ! :)
