### ISSUE TITLE
Need Upgrade of actual version

### ISSUE THREAD

**Issue by FlorianVouters** [Hormold/pubg#15]
Hello since yesterday i can't log in it says "AR:NEED_UPGRADE" with whatever version 

I saw the endpoint has changed and the parameter "fullClientVersion" no longer exists

But now, the version is 4.3.6.6 (today 06/29/2018) and the client can't connect with
4.3.6
4.3.6.6
4.3.6.6.0
4.3.6.8

On the http endpoint of PUBG we see the version : `"verreq": "4.3.6", `

`wss://prod-live-entry.playbattlegrounds.com/userproxy?provider=steam&ticket=140000003303D474250F624A6EBD4F1D010010012D08355B180000000100000002000000D91DDF5200000000ED81330536000000B200000032000000040000006EBD4F1D0100100120D20800D91DDF52D91DDF520000000087A92B5B0759475B01008440020000000000BBAD85EC1C3CAEDCD7A30600FE7BBBEA00B479B129142FA52139895567E45E07890A9296CF2F2E27DAAFA041C364C05D3D7E3893F7DC7D745205B30DB50143E8982A7CC399F2884ACB466FD5422ECD067D4914995CA76A78192FC655AD75400A8DD4BAD69F3DBD11FB904A61D7F4EC45557D3AF676440EEEE79768F50BA74467&playerNetId=76561198452030830&cc=FR&clientGameVersion=4.3.6.8&timezoneOffset=2
Error connecting: AR:NEED_UPGRADE`

Could someone help me ? Thanks !

**Comment by jobsfan** [comment]
Hello @Hormold ,
wish you all ok!

We encountered an error "**Error connecting: AR:INVALID_AUTH_DATA_ERROR**"  almost the same time as the above buddy. Do you have any solution about this?  We keep updating the version and the current v we use is **4.3.6.11**, I guess there are something changed on pubg server.

Looking forward to your reply.
Jobsfan

**Comment by FlorianVouters** [comment]
Yup, you need to change the param in the query, this is what we have, but it returns a Need Upgrade error : 
`'provider': 'steam', 'ticket': ticket, 'playerNetId': settings.steamId, 'cc': 'FR', 'clientGameVersion': settings.v, 'fullGameVersion' : settings.v_full, 'timezoneOffset' : '2', 'antiCheatSolution' : 'battleye'`
client game version we have 4.3.6 and full game version we have 4.3.6.11

It doesn't work for us, but hope it helps you !

**Comment by jobsfan** [comment]
@FlorianVouters , thank you!
With these 
**let query = { 'provider': 'steam', 'ticket': settings.ticket, 'playerNetId': settings.steamId, 'cc': 'RU', 'clientGameVersion': settings.v, 'fullClientGameVersion':settings.v2, 'timezoneOffset':'2','antiCheatSolution':'battleye'};** 

settings.v  4.3.6, and settings.v2 4.3.6.11

The error shows **AR:INVALID_AUTH_DATA_ERROR**

Before June 29th, it works well. I guess something changed about the pubg server.

**Comment by jobsfan** [comment]
@FlorianVouters 
I renewed the token and try another time, still the same error with before **Error connecting: AR:INVALID_AUTH_DATA_ERROR**

**Comment by FlorianVouters** [comment]
Your settings.steamId is defined ? You need to provide your steam ID, if it defined i don't know why i have got a Need Upgrade error while you got Invalid auth :/

**Comment by jobsfan** [comment]
@FlorianVouters  settings.steamid defined in the setting.js
I just clone @Hormold 's repository, the format of the setting is the same as his. Remember our web application works ok several days before.

**Comment by FlorianVouters** [comment]
Try to give the steam ID of your account in the settings.js

Look at here https://github.com/Hormold/pubg/issues/14

**Comment by jobsfan** [comment]
@FlorianVouters 
I do put our steamid in the setting.js! Remember our web application works ok several days before. It broke down just these several days.
Ps: our steamID64 is **76xxxxxxxxxxxxxx7** in setting.js.

**Comment by FlorianVouters** [comment]
Yup, for us too, but we just have a need upgrade error :/

**Comment by jobsfan** [comment]
@FlorianVouters 
Are you a web application developer? Or a exe-kind client programmer? 
Have you crawled the communication info with a wireshark software or a fiddle software and parsed the parameters in the communication? 

I am a web developer, and can not be able to crawl the desktop software communication and parsed them. Can you do this stuff?

**Comment by FlorianVouters** [comment]
I'm a student in it, so actually web application developer
Yeah, i tried to see any request made by PUBG with WireShark and i don't see anything, did you try ?

**Comment by pubgsnipe** [comment]
you can use fidler4 but need force game use localhost:8888 proxy
can do this but need a lot of time to download game via ADSL, so i waiting someone here

**Comment by jobsfan** [comment]
@FlorianVouters @pubgsnipe 
I works as a web developer, However, I have no pubg account. My work computer is so low deviced that can not run a pubg game. And we have our own desktop client developers with C C++ language, however they all can not help like died ones. LOL

**Comment by FlorianVouters** [comment]
I try to connect with this app to get URL (https://github.com/aaa4xu/pubg-lobby-proxy)

It gaves me this : `http://127.0.0.1:8001/wss://prod-live-entry.playbattlegrounds.com/userproxy/?provider=steam&ticket=14000000D1D0A042F74D2D3E1D8FEC0D010010010FE93D5B180000000100000002000000B53EFA560D01A8C09674570002000000B200000032000000040000001D8FEC0D0100100120D20800B53EFA560D01A8C0000000002392345BA341505B010084400200000000009ECFB05DD02206C0A2370FE8DFB40DB5FB1ED97BD3D9275C8E4C5C089610DF31F9B55A97F6E2939540987FA1465F97596635640A989072210FE70D8A92AE3ED12F139280773422934D440940EBD60FD82674C20F4CC29FB22A7161F447326BD2CC0ECA67D7A99FB7196F96357775C6391D9663373CC8AD4F48CE173BDD7AA29F&playerNetId={SteamID}&cc=FR&timezoneOffset=2&clientGameVersion=1.2.3&fullClientGameVersion=1.2.3.4&antiCheatSolution=be&authOption=`


It works for me try to set clientgameversion to 4.3.7 and full to 4.3.7.12

**Comment by jobsfan** [comment]
@FlorianVouters Thanks!!! It works for me too!!!

**Comment by jobsfan** [comment]
@FlorianVouters  I wanna to get infomations from wow, do you have ever acquired data for this game? And  tools to emulate the login like https://github.com/aaa4xu/pubg-lobby-proxy ?

**Comment by jobsfan** [comment]
@FlorianVouters 
Recently I got a jobs for acquire the WOW Chinese version data, like goods, props, pets etc. Can you give me any advices? 

Should I need to emulate the login to get the infomation like we do as pubg? By the way, there are more than 170 services for Chinese version WOW, and the information are not the same between them. You can not cross server to get infomation.

Wish you everthing good!
