### ISSUE TITLE
GetUserRecord not working anymore

### ISSUE THREAD

**Issue by Spechen** [Hormold/pubg#18]
Hello,

Since the last update with official ranking yesterday (2018-10-03), there is no return by the game, however the endpoint "GetBroUserStatesByNickname" works perfectly

I saw in the main.js file on the lobby of the game that it needs 4 param (e,t,n,i) and i don't know what are the last param
I've got the AccountID, the server (EU, NA, etc) and the mode (Solo, Duo, squad, etc) so i miss one param, does anyone have more information about that ?

Thanks !

**Comment by Spechen** [comment]
I found that the param need to be :
`AccountID, Server, Season, Mode`

But it doesn't work for any season i send

**Comment by lollka** [comment]
Current parameters:
AccountID, Platform, Season, Mode

Current season:
pc-2018-01

PC Platform:
steam

**Comment by Spechen** [comment]
Thanks, it works
