### ISSUE TITLE
Hello Hormold, It seems the interface entry.playbattlegrounds.com:81 stop serving

### ISSUE THREAD

**Issue by jobsfan** [Hormold/pubg#8]
9 hours ago, the pubg stats query via entry.playbattlegrounds.com:81 failed
We telnet the server with 81 port, however timeout all the time.
You are an expert on this, I am looking for your confirmation about this situation. is it surely we can not query pubg stats by this way and this interface now?

It seems that the GetBroUserStatesByNickname disabled.

**Comment by Hormold** [comment]
Yep, they use now a "wss://prod-live-entry.playbattlegrounds.com/userproxy"

**Comment by jobsfan** [comment]
Thank you @Hormold , does your code still work on when I change it as following?

        let server = 'prod-live-entry.playbattlegrounds.com'; //Use /health to check server health  
        let query = { 'provider': 'steam', 'ticket': settings.ticket, 'playerNetId': settings.steamId, 'cc': 'RU', 'clientGameVersion': settings.v };    
        let finalQuery = 'wss://' + server + '/userproxy?' + this.encodeQueryData(query);

**Comment by kolvin** [comment]
Struggling to connect on this! getting timeouts - as @Hormold said above they seem to use 'wss://prod-live-entry.playbattlegrounds.com/userproxy' to which i append the auth ticket to but im not getting much - any ideas @Hormold? @jobsfan Did you get any further with fixing your app when they stopped using the old domain?
